language: node_js
os:
  - linux
node_js: lts/*

# xvfb setup script for Linux that is necessary to run VS Code in headless Linux CI machines
before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
script:
  - npm run lint
  - npm run test
