
name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm install
      - run: sudo apt-get install xvfb
      - run: npm run lint
      - run: xvfb-run --auto-servernum npm test
        
        
   
